//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFinancialYear
    {
        public int Trid { get; set; }
        public string FinancialYear { get; set; }
        public string FYear { get; set; }
        public string Yearclose { get; set; }
    }
}
