//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mpacking
    {
        public int PackingId { get; set; }
        public string PackingCode { get; set; }
        public string PackingName { get; set; }
        public string AcFlag { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string Remark { get; set; }
    }
}
