//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPOTerm
    {
        public long POtermId { get; set; }
        public long CompanyId { get; set; }
        public string Module { get; set; }
        public string POtermCode { get; set; }
        public string POtermsName { get; set; }
        public string Description { get; set; }
        public string Acflag { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Remark { get; set; }
    }
}
