//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Msupplier
    {
        public long SupplierId { get; set; }
        public string Suppliercode { get; set; }
        public string BrokeragePer { get; set; }
        public string SupplierName { get; set; }
        public string SupplierAdress { get; set; }
        public string PhoneNo { get; set; }
        public string CellNo { get; set; }
        public string VATNo { get; set; }
        public string BSTNo { get; set; }
        public string PANNo { get; set; }
        public string TANNO { get; set; }
        public string EmailId { get; set; }
        public string FAXNo { get; set; }
        public string Acflag { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Remark { get; set; }
        public string AccoutNo { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string BankAdress { get; set; }
    }
}
